Adição do fluxo de login
wilcymartavares/store_pokemon pull request #2
Opened 2021-04-03 03:40 UTC by wilcymartavares

Yo, já tinha iniciado os trabalhos. Com isso o Git não aceitou que eu fizesse a criação e mudança de branchs, por isso mandei pra mesma da outra vez. Felizmente ela estava igual a main.

2021-04-05 14:53 UTC, yoannes requested changes

2021-04-05 14:53 UTC, yoannes commented on src/views/Login.vue
> +    </div>
Como voce colocou os dois divs um embaixo do outro, com a mesma classe e mesma variavel para mensagem de erro, pode economizar com:

```
    <div v-if="error.type === 'USERNAME' || error.type === 'PASSWORD'" class="signup-error">
      {{ error.msg }}
    </div>
```

2021-04-05 14:53 UTC, yoannes commented on src/views/Login.vue
> +S img {
Capaz que aqui deveria ser `.` ao inves de `S`

2021-04-07 03:20 UTC, wilcymartavares commented on src/views/Login.vue
> +    </div>
Efetuada a melhoria chefe.

2021-04-07 03:21 UTC, wilcymartavares commented on src/views/Login.vue
> +S img {
Essa tbm foi corrigida.

2021-04-08 23:11 UTC, merged